### ISSUE TITLE
Diggy fails on saving the txt file

### ISSUE THREAD

**Issue by solancer** [s0md3v/Diggy#6]
srinivasgowa@solancer Diggy % ./diggy.sh /Users/srinivasgowda/Downloads/BOMBitUP_v4.04.1.apk
     ___  _
    / _ \(_)__ ____ ___ __
   / // / / _ `/ _ `/ // /
  /____/_/\_, /\_, /\_, /
         /___//___//___/

./diggy.sh: line 29: temp: bad array subscript
./diggy.sh: line 30: -4: substring expression < 0
[!] Looks like this apk has been decompiled already.
[?] Decompile over the existing copy? [y/N] N
[~] Decompiling the apk
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at java.nio.file.Paths.get(Paths.java:84)
	at java.nio.file.TempFileHelper.<clinit>(TempFileHelper.java:50)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
	at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1353)
	at brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:45)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:94)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: java.security.PrivilegedActionException: sun.nio.fs.UnixException: No such file or directory
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
	... 17 more
Caused by: sun.nio.fs.UnixException: No such file or directory
	at sun.nio.fs.UnixNativeDispatcher.getcwd(Native Method)
	at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
	at sun.nio.fs.BsdFileSystem.<init>(BsdFileSystem.java:41)
	at sun.nio.fs.MacOSXFileSystem.<init>(MacOSXFileSystem.java:44)
	at sun.nio.fs.MacOSXFileSystemProvider.newFileSystem(MacOSXFileSystemProvider.java:45)
	at sun.nio.fs.MacOSXFileSystemProvider.newFileSystem(MacOSXFileSystemProvider.java:38)
	at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
	at sun.nio.fs.BsdFileSystemProvider.<init>(BsdFileSystemProvider.java:36)
	at sun.nio.fs.MacOSXFileSystemProvider.<init>(MacOSXFileSystemProvider.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:65)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
	... 20 more
[~] Extracting endpoints
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
awk: can't open file /Users/srinivasgowda/Desktop/Diggy/.txt
 source line number 1
[!] Endpoints saved in: /Users/srinivasgowda/Desktop/Diggy/.txt
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
srinivasgowa@solancer Diggy %
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
^Lshell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by EulerIExponent** [comment]
> srinivasgowa@solancer Diggy % ./diggy.sh /Users/srinivasgowda/Downloads/BOMBitUP_v4.04.1.apk
> ___ _
> / _ (_)__ ____ ___ __ / // / / _ `/ _ `/ // / /_**_/_/_, /_, /_, / /**_//_**//**_/
> 
> ./diggy.sh: line 29: temp: bad array subscript
> ./diggy.sh: line 30: -4: substring expression < 0
> [!] Looks like this apk has been decompiled already.
> [?] Decompile over the existing copy? [y/N] N
> [~] Decompiling the apk Exception in thread "main" java.lang.ExceptionInInitializerError at java.nio.file.FileSystems.getDefault(FileSystems.java:176) at java.nio.file.Paths.get(Paths.java:84) at java.nio.file.TempFileHelper.(TempFileHelper.java:50) at java.nio.file.Files.createTempFile(Files.java:897) at javax.imageio.stream.FileCacheImageInputStream.(FileCacheImageInputStream.java:102) at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69) at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357) at javax.imageio.ImageIO.read(ImageIO.java:1353) at brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:45) at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33) at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141) at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:94) at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258) at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129) at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124) at brut.apktool.Main.cmdDecode(Main.java:170) at brut.apktool.Main.main(Main.java:76) Caused by: java.security.PrivilegedActionException: sun.nio.fs.UnixException: No such file or directory at java.security.AccessController.doPrivileged(Native Method) at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96) at java.nio.file.FileSystems$DefaultFileSystemHolder.(FileSystems.java:90) ... 17 more Caused by: sun.nio.fs.UnixException: No such file or directory at sun.nio.fs.UnixNativeDispatcher.getcwd(Native Method) at sun.nio.fs.UnixFileSystem.(UnixFileSystem.java:67) at sun.nio.fs.BsdFileSystem.(BsdFileSystem.java:41) at sun.nio.fs.MacOSXFileSystem.(MacOSXFileSystem.java:44) at sun.nio.fs.MacOSXFileSystemProvider.newFileSystem(MacOSXFileSystemProvider.java:45) at sun.nio.fs.MacOSXFileSystemProvider.newFileSystem(MacOSXFileSystemProvider.java:38) at sun.nio.fs.UnixFileSystemProvider.(UnixFileSystemProvider.java:56) at sun.nio.fs.BsdFileSystemProvider.(BsdFileSystemProvider.java:36) at sun.nio.fs.MacOSXFileSystemProvider.(MacOSXFileSystemProvider.java:40) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at java.lang.Class.newInstance(Class.java:442) at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48) at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:65) at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108) at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89) at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98) at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96) ... 20 more [~] Extracting endpoints
> usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
> [-e pattern] [-f file] [--binary-files=value] [--color=when]
> [--context[=num]] [--directories=action] [--label] [--line-buffered]
> [--null] [pattern] [file ...]
> awk: can't open file /Users/srinivasgowda/Desktop/Diggy/.txt
> source line number 1
> [!] Endpoints saved in: /Users/srinivasgowda/Desktop/Diggy/.txt
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> srinivasgowa@solancer Diggy %
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> ^Lshell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Which operating system ?? If windows then which terminal emulator ?? 
If you are using Windows without terminal emulator then it will produce error ,reason for Windows command prompt you should use %cd% instead of getcwd try to replace getcwd by %cd% and try again
