### ISSUE TITLE
Removed all files from the directory

### ISSUE THREAD

**Issue by ghost** [s0md3v/Diggy#8]
Used it simply on an already decompiled apk and it went to delete all the files from that directory and threw this error - 

./diggy.sh: line 29: -4: substring expression < 0
[!] Looks like this apk has been decompiled already.
[?] Decompile over the existing copy? [y/N] y
Decompiling the apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.nio.file.NoSuchFileException: apk/1
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:315)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.nio.file.NoSuchFileException: apk/1
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:313)
	... 3 more
Caused by: java.nio.file.NoSuchFileException: apk/1
	at sun.nio.fs.UnixException.translateToIOException(java.base@9-internal/UnixException.java:92)
	at sun.nio.fs.UnixException.rethrowAsIOException(java.base@9-internal/UnixException.java:111)
	at sun.nio.fs.UnixException.rethrowAsIOException(java.base@9-internal/UnixException.java:116)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(java.base@9-internal/UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(java.base@9-internal/UnixFileSystemProvider.java:145)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(java.base@9-internal/LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(java.base@9-internal/Files.java:1738)
	at java.util.zip.ZipFile$Source.get(java.base@9-internal/ZipFile.java:924)
	at java.util.zip.ZipFile.<init>(java.base@9-internal/ZipFile.java:213)
	at java.util.zip.ZipFile.<init>(java.base@9-internal/ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(java.base@9-internal/ZipFile.java:159)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
 Extracting endpoints
awk: cannot open /home/user/Downloads/.txt (No such file or directory)

**Comment by trieulieuf9** [comment]
Yep, the same for me.

**Comment by paulschwahn** [comment]
Wiped my entire downloads folder...

**Comment by jay3oh5** [comment]
I ran it on mac and it wiped all my Hombrew and zsh related items. Same as all of you.

**Comment by mustafairan** [comment]
My lost is not big but ... damn man really?

**Comment by n0kovo** [comment]
I literally just lost all my password manager databases, code project, music projects, notes, bookmarks, data I've been collecting for at least 5 years and so much more completely irreplaceable stuff.
I am beyond furious. FUCK you, @s0md3v, you FUCKING PIECE OF SHIT!!!
